# Bot Configuration Settings

# API Settings
api:
  rate_limit:
    max_blocks_per_day: 1000
    cooldown_period: 60  # seconds
    retry_delay: 5  # seconds

# Bot Detection Settings
bot_detection:
  # Thresholds
  min_account_age_days: 7
  min_followers: 5
  max_following_ratio: 5
  min_tweets: 3
  bot_probability_threshold: 0.6
  whitelist: []
  blacklist: []

  # Image Analysis Settings
  image_analysis:
    enabled: true
    min_image_size: 100
    max_image_size: 1000
    face_detection_threshold: 0.6
    edge_detection_threshold: 100
    suspicious_face_count: [0, 2]  # Range of suspicious face counts
    min_edge_density: 0.01
    max_edge_density: 0.5
    min_unique_colors: 10
    max_unique_colors: 1000
    image_download_timeout: 10  # seconds

  # Spam word patterns
  spam_words:
    - "hot"
    - "dm"
    - "onlyfans"
    - "porn"
    - "xxx"
    - "adult"
    - "escort"
    - "dating"
    - "follow back"
    - "follow me"
    - "check my bio"
    - "link in bio"
    - "click here"
    - "free"
    - "promo"
    - "discount"
    - "offer"
    - "deal"
    - "sale"
    - "crypto"
    - "bitcoin"
    - "investment"
    - "earn money"
    - "make money"
    - "work from home"
    - "passive income"
    - "get rich"
    - "millionaire"
    - "wealth"

  # Suspicious username patterns (regex)
  suspicious_patterns:
    - "^[0-9]+$"  # All numbers
    - "^[a-zA-Z]+[0-9]+$"  # Letters followed by numbers
    - "^[0-9]+[a-zA-Z]+$"  # Numbers followed by letters
    - ".*bot.*"  # Contains "bot"
    - ".*spam.*"  # Contains "spam"
    - ".*fake.*"  # Contains "fake"
    - ".*follow.*back.*"  # Contains "follow back"
    - ".*dm.*"  # Contains "dm"
    - ".*promo.*"  # Contains "promo"
    - ".*crypto.*"  # Contains "crypto"

  # URL patterns to detect in descriptions
  url_patterns:
    - "https?://(?:www\\.)?bit\\.ly/\\w+"  # Bitly links
    - "https?://(?:www\\.)?t\\.co/\\w+"  # Twitter's t.co links
    - "https?://(?:www\\.)?goo\\.gl/\\w+"  # Google's goo.gl links
    - "https?://(?:www\\.)?tinyurl\\.com/\\w+"  # TinyURL links
    - "https?://(?:www\\.)?cutt\\.ly/\\w+"  # Cutt.ly links
    - "https?://(?:www\\.)?adf\\.ly/\\w+"  # AdFly links
    - "https?://(?:www\\.)?linktr\\.ee/\\w+"  # Linktree links
    - "https?://(?:www\\.)?bio\\.link/\\w+"  # Bio.link links

# Behavior Analysis Settings
behavior_analysis:
  min_interaction_interval: 1  # seconds
  max_interactions_per_hour: 50
  suspicious_pattern_threshold: 0.8
  content_similarity_threshold: 0.9
  max_identical_tweets: 3
  max_following_ratio: 10
  max_followers_per_day: 100
  unusual_hours:
    start: 2  # 2 AM
    end: 6    # 6 AM
  activity_thresholds:
    max_active_hours: 20
    min_active_hours: 3

# Monitoring Settings
monitoring:
  enabled: true
  check_interval: 300  # 5 minutes
  retention_days: 30
  thresholds:
    system:
      cpu_warning: 85
      cpu_critical: 95
      memory_warning: 75
      memory_critical: 90
      disk_warning: 80
      disk_critical: 90
    performance:
      response_time_warning: 1.5  # seconds
      response_time_critical: 2.0
      error_rate_warning: 5  # percentage
      error_rate_critical: 10
    detection:
      false_positive_warning: 0.5  # percentage
      false_positive_critical: 1.0
      accuracy_warning: 95  # percentage
      accuracy_critical: 90
    api:
      rate_limit_warning: 75  # percentage of limit used
      rate_limit_critical: 90
      failed_requests_warning: 5  # percentage
      failed_requests_critical: 10
  alerts:
    enabled: true
    channels:
      slack:
        enabled: true
        webhook_url: "${SLACK_WEBHOOK_URL}"
        channel: "#bot-blocker-alerts"
        username: "Bot Blocker Monitor"
        icon_emoji: ":robot_face:"
      email:
        enabled: false
        smtp_server: ""
        smtp_port: 587
        sender: ""
        recipients: []
    levels:
      info:
        color: "#2196F3"
        notify: false
      warning:
        color: "#FFC107"
        notify: true
      critical:
        color: "#F44336"
        notify: true
    cooldown:
      warning: 1800  # 30 minutes
      critical: 300   # 5 minutes
  metrics:
    collection:
      enabled: true
      interval: 60  # 1 minute
      batch_size: 100
    export:
      format: "csv"
      directory: "metrics"
      interval: 3600  # 1 hour
    dashboard:
      enabled: true
      update_interval: 300  # 5 minutes
      port: 8080
  enable_alerts: true
  alert_interval: 3600  # 1 hour in seconds
  alert_cooldown: 900  # 15 minutes in seconds

# Scanning Settings
scanning:
  # Number of items to fetch per scan
  mentions_count: 200
  followers_count: 200
  likes_count: 200
  
  # Scan frequency (in minutes)
  scan_interval: 15
  max_retries: 3
  timeout: 30

# Reporting Settings
reporting:
  directory: reports
  retention_days: 90
  formats:
    - json
    - csv
  schedule:
    weekly:
      enabled: true
      day: monday
      time: "00:00"
    monthly:
      enabled: true
      day: 1
      time: "00:00"
  metrics:
    blocks:
      enabled: true
      threshold: 1000
    accuracy:
      enabled: true
      threshold: 0.95
    error_rate:
      enabled: true
      threshold: 0.05
    resource_usage:
      enabled: true
      thresholds:
        cpu: 80
        memory: 80
        disk: 80
  export:
    enabled: true
    format: json
    compression: true
    batch_size: 1000
    retention_days: 90

# Whitelist/Blacklist
lists:
  whitelist: []  # List of usernames to never block
  blacklist: []  # List of usernames to always block

# Logging Settings
logging:
  level: "INFO"
  file: "bot_blocker.log"
  max_size: 10485760  # 10MB
  backup_count: 5 